apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-sandbox-controller
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: clusters/global/operators/agent-sandbox-controller
    repoURL: 'https://github.com/openshift-online/bootstrap-hyperfleet'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
