---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
spec:
  availabilityConfig: High
  enableClusterBackup: false
  overrides:
    components:
    - name: app-lifecycle
      enabled: true
    - name: cluster-backup
      enabled: true
    - name: cluster-lifecycle
      enabled: true
    - name: cluster-permission
      enabled: true
    - name: console
      enabled: true
    - name: grc
      enabled: true
    - name: insights
      enabled: true
    - name: multicluster-observability
      enabled: true
    - name: search
      enabled: true
    - name: submariner-addon
      enabled: true
    - name: volsync
      enabled: true
  infrastructureCustomizations:
    infrastructureProviders:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: vsphere
      enabled: true
    - name: openstack
      enabled: true
    - name: baremetal
      enabled: true
