apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agent-sandbox-controller/
  - cloudnative-pg/
  - grafana-operator/
  - keycloak-operator/
  - openshift-gitops/
  - openshift-pipelines/
  - user-workload-monitoring/
  - vault/
