apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: test-workspace-sharing
  namespace: hub-provisioner
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: write-file
      workspaces:
        - name: shared-data
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: shared-data
        steps:
          - name: write
            image: registry.redhat.io/ubi9/ubi-minimal
            script: |
              #!/bin/bash
              set -e
              echo "📝 Writing file to shared workspace..."
              echo "Hello from task 1 at $(date)" > $(workspaces.shared-data.path)/test-file.txt
              echo "✅ File written to: $(workspaces.shared-data.path)/test-file.txt"
              echo "Contents:"
              cat $(workspaces.shared-data.path)/test-file.txt
              ls -la $(workspaces.shared-data.path)/
    
    - name: read-file
      runAfter:
        - write-file
      workspaces:
        - name: shared-data
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: shared-data
        steps:
          - name: read
            image: registry.redhat.io/ubi9/ubi-minimal
            script: |
              #!/bin/bash
              set -e
              echo "📖 Reading file from shared workspace..."
              echo "Workspace path: $(workspaces.shared-data.path)"
              echo "Directory contents:"
              ls -la $(workspaces.shared-data.path)/
              
              if [ -f "$(workspaces.shared-data.path)/test-file.txt" ]; then
                echo "✅ File found! Contents:"
                cat $(workspaces.shared-data.path)/test-file.txt
                echo "✅ SUCCESS: Workspace sharing works!"
                exit 0
              else
                echo "❌ FAILED: File not found in shared workspace"
                exit 1
              fi
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-workspace-sharing-run-2
  namespace: hub-provisioner
spec:
  pipelineRef:
    name: test-workspace-sharing
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
