apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cluster-remove-pipeline
  namespace: hub-provisioner
  annotations:
    description: "Pipeline for removing cluster from repository and triggering bootstrap"
spec:
  description: >-
    Cluster removal pipeline that removes cluster directory from repository,
    commits the changes to GitHub, and triggers bootstrap pipeline to reconcile.
  params:
    - name: cluster-name
      type: string
      description: "Name of the cluster to remove"
  tasks:
    - name: remove-from-repo-and-commit
      taskSpec:
        params:
          - name: cluster-name
        steps:
          - name: remove
            image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel9@sha256:cbd89c531953a43b8055bda72f7696be80f57fd1d782567a91d82e0fbcb3d26d
            env:
              - name: SSH_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: github-repo-credentials
                    key: ssh-privatekey
            script: |
              #!/bin/bash
              set -e
              
              echo "🚀 Starting cluster removal workflow..."
              echo "Cluster: $(params.cluster-name)"
              
              # Setup SSH directory and key
              SSH_DIR=/tekton/home/.ssh
              mkdir -p "$SSH_DIR"
              chmod 700 "$SSH_DIR"
              
              SSH_KEY_FILE="$SSH_DIR/id_rsa"
              echo "$SSH_PRIVATE_KEY" > "$SSH_KEY_FILE"
              chmod 600 "$SSH_KEY_FILE"
              
              # Add GitHub to known hosts
              ssh-keyscan github.com >> "$SSH_DIR/known_hosts" 2>/dev/null
              
              # Configure git identity
              export GIT_AUTHOR_NAME="Hub Provisioner Pipeline"
              export GIT_AUTHOR_EMAIL="hub-provisioner@bootstrap.red-chesterfield.com"
              export GIT_COMMITTER_NAME="Hub Provisioner Pipeline"
              export GIT_COMMITTER_EMAIL="hub-provisioner@bootstrap.red-chesterfield.com"
              
              echo "✅ SSH key configured"
              
              # Clone repository
              echo "📦 Cloning repository..."
              WORK_DIR=$(mktemp -d)
              cd "$WORK_DIR"
              GIT_SSH_COMMAND="ssh -i $SSH_KEY_FILE -o StrictHostKeyChecking=no" \
                git clone git@github.com:openshift-online/bootstrap-hyperfleet.git .
              
              echo "🗑️ Running bin/cluster-remove..."
              bash bin/cluster-remove "$(params.cluster-name)"
              
              # Commit and push changes
              echo "📝 Committing changes..."
              git add -A
              
              if git diff --cached --quiet; then
                echo "ℹ️ No changes to commit"
                exit 0
              fi
              
              git commit -m "Remove cluster $(params.cluster-name)" \
                -m "Automated cluster removal via pipeline" \
                -m "🤖 Generated with Claude Code" \
                -m "" \
                -m "Co-Authored-By: Claude <noreply@anthropic.com>"
              
              GIT_SSH_COMMAND="ssh -i $SSH_KEY_FILE -o StrictHostKeyChecking=no" \
                git push origin main
              
              echo "✅ Changes committed and pushed to GitHub"
      params:
        - name: cluster-name
          value: "$(params.cluster-name)"
    
    - name: trigger-bootstrap
      runAfter:
        - remove-from-repo-and-commit
      taskSpec:
        params:
          - name: cluster-name
        steps:
          - name: trigger
            image: registry.redhat.io/openshift4/ose-cli
            script: |
              #!/bin/bash
              set -e
              
              echo "🔄 Triggering bootstrap pipeline to reconcile changes..."
              
              if oc get pipeline bootstrap-pipeline -n hub-provisioner &>/dev/null; then
                oc create -f - <<EOF
              apiVersion: tekton.dev/v1
              kind: PipelineRun
              metadata:
                generateName: bootstrap-post-removal-
                namespace: hub-provisioner
              spec:
                pipelineRef:
                  name: bootstrap-pipeline
                timeout: 1h
              EOF
                echo "✅ Bootstrap pipeline triggered successfully"
              else
                echo "ℹ️  Bootstrap pipeline not found - skipping trigger"
                echo "   ArgoCD will auto-sync the changes"
              fi
      params:
        - name: cluster-name
          value: "$(params.cluster-name)"
    
  finally:
    - name: removal-summary
      taskSpec:
        params:
          - name: cluster-name
        steps:
          - name: summary
            image: registry.redhat.io/openshift4/ose-cli
            script: |
              #!/bin/bash
              
              echo "📋 Cluster Removal Summary"
              echo "=========================="
              echo "Cluster Name: $(params.cluster-name)"
              echo "Timestamp: $(date -Iseconds)"
              echo ""
              echo "✅ Cluster directory removed from repository"
              echo "✅ Changes committed to GitHub"
              echo "✅ Bootstrap pipeline triggered"
              echo ""
              echo "📌 Next steps:"
              echo "   1. Bootstrap pipeline reconciles ArgoCD changes"
              echo "   2. ArgoCD prunes cluster resources"
              echo "   3. Cluster removal complete"
              echo "=========================="
      params:
        - name: cluster-name
          value: "$(params.cluster-name)"
