apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-repo-credentials
  namespace: hub-provisioner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: github-repo-credentials
    creationPolicy: Owner
    template:
      data:
        .git-credentials: "{{ printf \"https://%s:%s@github.com\" .username .token | b64enc }}"
  data:
  - secretKey: username
    remoteRef:
      key: github-credentials
      property: username
  - secretKey: token
    remoteRef:
      key: github-credentials
      property: token
