apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-repo-credentials
  namespace: hub-provisioner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: github-repo-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: "{{ .ssh_privatekey }}"
        ssh-publickey: "{{ .ssh_publickey }}"
  data:
  - secretKey: ssh_privatekey
    remoteRef:
      key: github-credentials
      property: ssh-privatekey
  - secretKey: ssh_publickey
    remoteRef:
      key: github-credentials
      property: ssh-publickey
