apiVersion: v1
metadata:
  name: 'ocp-01-hyp'
baseDomain: hyperfleet.bootstrap.red-chesterfield.com
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      rootVolume:
        iops: 4000
        size: 100
        type: io1
      type: m5.2xlarge
compute:
  - hyperthreading: Enabled
    architecture: amd64
    name: 'worker'
    replicas: 2
    platform:
      aws:
        rootVolume:
          iops: 2000
          size: 100
          type: io1
        type: m5.2xlarge
networking:
  networkType: OVNKubernetes
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.0.0.0/16
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: us-west-2
pullSecret: "" # skip, hive will inject based on it's secrets
