apiVersion: v1
kind: Namespace
metadata:
  name: keycloak-system
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    openshift.io/display-name: "Keycloak Operator"
