apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-01-hyp-eso
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    external-repo: "true"
spec:
  destination:
    server: https://api.ocp-01-hyp.bootstrap.red-chesterfield.com:6443
    namespace: external-secrets
  source:
    path: ''
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.18.1
    chart: external-secrets
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
