apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-repo-credentials
  namespace: openshift-gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: github-repo-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/ssh-auth
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:openshift-online/bootstrap-hyperfleet.git
        sshPrivateKey: "{{ .ssh_privatekey }}"
  data:
  - secretKey: ssh_privatekey
    remoteRef:
      key: github-credentials
      property: ssh-privatekey
  - secretKey: ssh_publickey
    remoteRef:
      key: github-credentials
      property: ssh-publickey
