apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-repo-credentials
  namespace: openshift-gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-repo-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/openshift-online/bootstrap-hyperfleet
        username: "{{ .username }}"
        password: "{{ .token }}"
  data:
  - secretKey: username
    remoteRef:
      key: github-credentials
      property: username
  - secretKey: token
    remoteRef:
      key: github-credentials
      property: token
