apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hypershell-stage
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  destination:
    name: in-cluster
    namespace: hypershell-stage
  project: default
  source:
    path: bases/hypershell/overlays/stage
    repoURL: 'https://github.com/openshift-online/bootstrap-hyperfleet'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
