apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - hypershell-int.application.yaml
  - hypershell-stage.application.yaml
  - hypershell-prod.application.yaml
