apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - api-server.yaml
  - controller.yaml
  - controller-rbac.yaml
  - keycloak.yaml
  - route.yaml

configurations:
  - name-reference.yaml

configMapGenerator:
  - name: keycloak-realm-config
    files:
      - hypershell-realm.json
    options:
      disableNameSuffixHash: true
