apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cluster-remove-ocp-789
  namespace: hub-provisioner
  labels:
    tekton.dev/pipeline: cluster-remove-pipeline
    cluster: ocp-789
spec:
  pipelineRef:
    name: cluster-remove-pipeline
  params:
    - name: cluster-name
      value: ocp-789
  timeout: 1h
