apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - openshift-gitops/
  - user-workload-monitoring/
  - cloudnative-pg/
  - keycloak-operator/
  - grafana-operator/
  - agent-sandbox-controller/
  - openshift-pipelines/
  - vault/
  - ../eso/global/
  - hub-provisioner/

