apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hypershell-int

resources:
  - ../../base

namePrefix: int-

patches:
  - target:
      kind: Namespace
      name: hypershell
    patch: |
      - op: replace
        path: /metadata/name
        value: hypershell-int
      - op: replace
        path: /metadata/annotations/openshift.io~1display-name
        value: "HyperShell Integration"

  - target:
      kind: Deployment
      name: hypershell-controller
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "int-hypershell-api-server:9000"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "http://int-hypershell-api-server:8000"
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "hypershell-int"
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "hypershell-cluster-4c28435107377e996c6eb39230b7bcf5-0000.us-east.containers.appdomain.cloud"

  - target:
      kind: ClusterRoleBinding
      name: hypershell-controller
    patch: |
      - op: replace
        path: /subjects/0/namespace
        value: hypershell-int

  - target:
      kind: Deployment
      name: keycloak
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "https://int-keycloak-hypershell-int.hypershell-cluster-4c28435107377e996c6eb39230b7bcf5-0000.us-east.containers.appdomain.cloud"

  - target:
      kind: Secret
      name: hypershell-db
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: hypershell-db
      stringData:
        db.host: "int-hypershell-postgres"

  - target:
      kind: Secret
      name: sso-credentials
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: sso-credentials
      stringData:
        KEYCLOAK_ADMIN_PASSWORD: "admin"
        SSO_ISSUER_URL: "http://int-keycloak-service:8080/realms/hypershell"
        SSO_FRONTEND_ISSUER_URL: "https://int-keycloak-hypershell-int.hypershell-cluster-4c28435107377e996c6eb39230b7bcf5-0000.us-east.containers.appdomain.cloud/realms/hypershell"
        SSO_CLIENT_SECRET: "dev-secret-do-not-use-in-prod"
        SSO_REDIRECT_URI: "https://int-hypershell-api-hypershell-int.hypershell-cluster-4c28435107377e996c6eb39230b7bcf5-0000.us-east.containers.appdomain.cloud/*"

images:
  - name: quay.io/redhat-services-prod/hcm-eng-prod-tenant/hypershell-main/hypershell-api-server-main
    newTag: latest
  - name: quay.io/redhat-services-prod/hcm-eng-prod-tenant/hypershell-main/hypershell-control-plane-main
    newTag: latest
