apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-provisioner
  namespace: hub-provisioner
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  destination:
    name: in-cluster
    namespace: bootstrap
  project: default
  source:
    path: pipelines/hub-provisioner/global
    repoURL: 'https://github.com/openshift-online/bootstrap'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true