apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: clusters/global/operators/grafana-operator
    repoURL: 'https://github.com/openshift-online/bootstrap'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
