apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Agent Sandbox Controller"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: agent-sandbox-system
