---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-555-provisioning
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  generators:
  - list:
      elements:
      - component: cluster
        path: clusters/ocp-555
        destination: https://kubernetes.default.svc
        syncWave: "10"
  
  template:
    metadata:
      name: ocp-555-{{component}}
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
      labels:
        cluster: ocp-555
        phase: provisioning
    spec:
      project: default
      source:
        repoURL: https://github.com/openshift-online/bootstrap-hyperfleet
        path: '{{path}}'
        targetRevision: main
      destination:
        server: '{{destination}}'
      syncPolicy:
        automated:
          selfHeal: true
          allowEmpty: false
        prune: false
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-555-managed
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  generators:
  - list:
      elements:
      - component: operators
        path: operators/openshift-pipelines/ocp-555
        destination: https://api.ocp-555.bootstrap.red-chesterfield.com:6443
        syncWave: "10"
      - component: pipelines
        path: pipelines/cloud-infrastructure-provisioning/ocp-555
        destination: https://api.ocp-555.bootstrap.red-chesterfield.com:6443
        syncWave: "20"
      - component: deployments
        path: deployments/ocm/ocp-555
        destination: https://api.ocp-555.bootstrap.red-chesterfield.com:6443
        syncWave: "30"
  
  template:
    metadata:
      name: ocp-555-{{component}}
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
      labels:
        cluster: ocp-555
        phase: managed
    spec:
      project: default
      source:
        repoURL: https://github.com/openshift-online/bootstrap-hyperfleet
        path: '{{path}}'
        targetRevision: main
      destination:
        server: '{{destination}}'
      syncPolicy:
        automated:
          selfHeal: true
          allowEmpty: false
        prune: false
        syncOptions:
        - CreateNamespace=true
