apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-03-applications
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - component: cluster
        path: clusters/ocp-03
        destination: https://api.ocp-01-hyp.bootstrap.red-chesterfield.com:6443
        syncWave: "1"
      - component: operators
        path: operators/openshift-pipelines/ocp-03
        destination: ocp-03
        syncWave: "2"
      - component: pipelines-cloud-infrastructure-provisioning
        path: pipelines/cloud-infrastructure-provisioning/ocp-03
        destination: ocp-03
        syncWave: "4"
      - component: deployments-ocm
        path: deployments/ocm/ocp-03
        destination: ocp-03
        syncWave: "5"
  template:
    metadata:
      name: ocp-03-{{component}}
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/openshift-online/bootstrap
        path: '{{path}}'
        targetRevision: main
      destination:
        server: '{{destination}}'
      syncPolicy:
        automated:
          selfHeal: true
          allowEmpty: false
        prune: false
