apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: patch-me-see-overlays-dir
    newName: quay.io/redhat-services-prod/hcm-eng-prod-tenant/hypershell-main/agent-sandbox-controller
    newTag: v0.5.1
